export const data = {
  name: "Vaibhav",
  tagline: "Building intelligent systems that solve real-world problems.",
  titles: ["AI Engineer", "Machine Learning Engineer", "GenAI Developer", "Backend Developer", "Researcher"],
  bio: "I'm an AI & Machine Learning Engineer passionate about building intelligent systems that bridge research and real-world impact. From deepfake detection to electricity forecasting, I craft solutions that matter.",
  email: "vikashvaibhav584@gmail.com",
  linkedin: "https://www.linkedin.com/in/vaibhav-rajiv-kumar-53177a333/",
  twitter: "https://twitter.com/Vaibhav586",
  medium: "https://medium.com",
  resume: "/resume.pdf",

  stats: [
    { label: "Projects", value: 12, icon: "Code2" },
    { label: "Research", value: 2, icon: "BookOpen" },
    { label: "Internships", value: 3, icon: "Briefcase" },
    { label: "Hackathons", value: 8, icon: "Trophy" },
    { label: "Leadership", value: 4, icon: "Users" },
    { label: "Certifications", value: 10, icon: "Award" },
  ],

  timeline: [
    { year: "2022", event: "Started AI Journey" },
    { year: "2024", event: "AI Intern @ OpenRAG" },
    { year: "2025", event: "Cloud Security Intern @ Zero Trust Cloud"},
    { year: "2026", event: "Operation Intern @ ClearTax" },
    { year: "2026", event: "IEEE Research Publication" },
    { year: "2026", event: "Btech in CSE-AIML @ SRMIST" },
  ],

  skills: {
    Programming: ["Python", "TypeScript", "JavaScript", "SQL", "Bash"],
    AI: ["PyTorch", "Scikit-learn", "LangChain", "OpenAI API", "HuggingFace", "RAG", "LLMs"],
    Backend: ["FastAPI", "Node.js", "REST APIs"],
    Frontend: ["React", "Next.js", "Tailwind CSS", "Framer Motion"],
    Database: ["MySQL", "MongoDB", "ChromaDB"],
    Cloud: ["AWS", "Vercel", "Docker", "Kubernetes"],
    DevOps: ["Git", "GitHub Actions", "CI/CD", "Linux", "Nginx"],
    Tools: ["VS Code", "Jupyter", "Postman", "Figma", "Notion"],
  },

  projects: [
    {
      id: "electricity-forecasting",
      title: "AI Electricity Forecasting",
      description: "LSTM-based time series model forecasting electricity demand with 94% accuracy using weather and historical data.",
      tech: ["Python", "PyTorch", "LSTM", "FastAPI", "React"],
      demo: "",
      color: "#3B82F6",
      problem: "Electricity grids face instability due to unpredictable demand fluctuations.",
      solution: "Built an LSTM neural network trained on 5 years of historical data with weather features.",
      metrics: ["94% accuracy", "15% grid efficiency improvement", "Real-time predictions"],
      features: ["Time series forecasting", "Weather integration", "Real-time dashboard", "REST API"],
    },
    {
      id: "deepfake-detection",
      title: "Deepfake Detection System",
      description: "CNN + Vision Transformer hybrid model detecting deepfake videos with 97% accuracy. IEEE published research.",
      tech: ["Python", "PyTorch", "ViT", "CNN", "OpenCV"],
      demo: "",
      color: "#8B5CF6",
      problem: "Deepfake media poses serious threats to digital trust and security.",
      solution: "Hybrid CNN-ViT architecture analyzing spatial and temporal inconsistencies.",
      metrics: ["97% accuracy", "IEEE Published", "Real-time detection"],
      features: ["Video analysis", "Frame-level detection", "Confidence scoring", "Batch processing"],
    },
    {
      id: "sql-ai-assistant",
      title: "Conversational SQL AI Assistant",
      description: "Natural language to SQL converter with multi-turn conversation, schema awareness, and query optimization.",
      tech: ["Python", "LangChain", "OpenAI", "FastAPI", "PostgreSQL"],
      demo: "",
      color: "#06B6D4",
      problem: "Non-technical users struggle to query databases without SQL knowledge.",
      solution: "LLM-powered assistant with schema context, memory, and query validation.",
      metrics: ["95% query accuracy", "Multi-turn context", "10+ DB schemas"],
      features: ["Natural language queries", "Schema awareness", "Query optimization", "Audit logging"],
    },
    {
      id: "ai-surveillance-robot",
      title: "AI Surveillance Robot",
      description: "Autonomous robot with real-time object detection, face recognition, and threat assessment using edge AI.",
      tech: ["Python", "YOLOv8", "Raspberry Pi", "OpenCV", "MQTT"],
      demo: "",
      color: "#10B981",
      problem: "Traditional surveillance systems lack intelligent threat detection.",
      solution: "Edge AI robot with YOLOv8 for real-time detection and autonomous navigation.",
      metrics: ["30fps detection", "95% face recognition", "Autonomous navigation"],
      features: ["Object detection", "Face recognition", "Threat assessment", "Remote monitoring"],
    },
  ],

  experience: [
    {
      company: "ClearTax",
      role: "Operation Intern",
      duration: "April 2026 – July 2026",
      description: "Built RAG-based document intelligence system reducing manual review time by 60%. Developed LLM pipelines for tax document processing.",
      skills: ["Python", "LangChain", "RAG", "OpenAI", "FastAPI"],
      achievements: ["60% reduction in manual review", "Processed 10K+ documents", "Deployed to production"],
      logo: "CT",
      color: "#3B82F6",
    },
    {
      company: "OpenRAG",
      role: "AI Intern",
      duration: "Jan 2024 – Apr 2024",
      description: "Optimized RAG pipelines for enterprise knowledge bases. Implemented vector search with Pinecone and ChromaDB.",
      skills: ["Python", "Pinecone", "ChromaDB", "LangChain", "Docker"],
      achievements: ["40% faster retrieval", "Built 3 production pipelines", "Reduced hallucinations by 35%"],
      logo: "OR",
      color: "#8B5CF6",
    },
    {
      company: "Zero Trust Cloud",
      role: "Cloud Security Intern",
      duration: "Aug 2023 – Nov 2023",
      description: "Implemented zero-trust security architecture on AWS. Automated compliance checks and security monitoring.",
      skills: ["AWS", "Python", "Terraform", "Security", "CI/CD"],
      achievements: ["Zero security incidents", "Automated 80% of compliance checks", "Reduced attack surface by 45%"],
      logo: "ZT",
      color: "#06B6D4",
    },
  ],

  research: [
    {
      title: "AI Surveillance Robot",
      conference: "17th International Conference on Recent Engineering and Technology (ICRET 2026)",
      organizer: "Sai Vidya Institute of Technology",
      collaborators: "In collaboration with Samarkand State University (Uzbekistan) and OSIET, India",
      abstract: "Presented a research paper on an AI-powered surveillance robot that leverages computer vision and artificial intelligence for intelligent monitoring, threat detection, and autonomous surveillance capabilities.",
      year: "2026",
      status: "Presented",
      tags: [
        "Artificial Intelligence",
        "Computer Vision",
        "Robotics",
        "Surveillance Systems",
        "Machine Learning",
      ],
    },
  ],

  leadership: [
    {
      role: "Committee Head",
      org: "AI/ML Club",
      duration: "2023 – 2024",
      description: "Led a team of 30+ members organizing workshops, hackathons, and research sessions.",
      events: 15,
      students: 200,
    },
    {
      role: "Discipline Convenor",
      org: "National level Fest",
      duration: "2025",
      description: "Managed discipline and coordination for 20k+ participant Milan festival.",
      events: 8,
      students: 20000,
    },
    {
      role: "Class Representative",
      org: "SRMIST",
      duration: "2022-2026",
      description: "acting as the primary liaison between faculty and students while coordinating academic communication and class activities.",
      students: 68,
    },
  ],

  achievements: [
    { title: "Ideathon Winner", desc: "1st place among 200+ teams for AI-powered solution", color: "#F59E0B" },
    { title: "Appathon Winner", desc: "Best App award for AI surveillance system", color: "#6B7280" },
    { title: "Research Presenter", desc: "Presented at IEEE ICCCNT 2024 conference", color: "#3B82F6" },
    { title: "Hackathon Finalist", desc: "Top 5 in national-level AI hackathon", color: "#8B5CF6" },
  ],

  certifications: [
    { name: "Oracle Cloud Infrastructure 2024 Certified AI Foundations Associate", issuer: "Oracle", date: "2025", logo: "Oracle", credential: "CE92DD53D3E37AF7F829E1A43304E2B83172D5C2A0CC396E76D" },
    { name: "Introduction to AI", issuer: "Google", date: "2025", logo: "Google", credential: "VRPZU68L6OQF" },
    { name: "SQL Foundations", issuer: "Microsoft", date: "2025", logo: "Microsoft", credential: "BSKIGTP5Q892" },
    { name: "Responsive Web Design", issuer: "freeCodeCamp", date: "2025", logo: "freeCodeCamp", credential: "vaibhav_584-rwd" },
    { name: "Google Cloud Computing Foundations", issuer: "Google", date: "2025", logo: "Google", credential: "https://www.credly.com/badges/7afd0590-7f27-49a8-ab8a-5310ceab7e5e/public_url" },
  ],

  now: {
    building: "AI-powered portfolio with RAG chatbot",
    learning: "Multimodal LLMs & Diffusion Models",
    reading: "Attention Is All You Need (revisiting)",
    listening: "Lo-fi Hip Hop",
    watching: "Andrej Karpathy lectures",
    available: true,
  },

  chatbot: {
    about: "Vaibhav is an AI & Machine Learning Engineer with expertise in LLMs, computer vision, and backend development. He has published IEEE research on deepfake detection and built production AI systems.",
    skills: "Python, PyTorch, TensorFlow, LangChain, OpenAI API, FastAPI, React, Next.js, AWS, Docker, PostgreSQL, and more.",
    experience: "AI/ML Intern at ClearTax (RAG systems), Operations Intern at OpenRAG (vector search), Cloud Security Intern at Zero Trust Cloud.",
    projects: "AI Electricity Forecasting (94% accuracy), Deepfake Detection (97% accuracy, IEEE published), SQL AI Assistant, AI Surveillance Robot.",
    research: "Published IEEE paper on Hybrid CNN-ViT for Deepfake Detection at ICCCNT 2024 with 12 citations.",
    contact: "Reach Vaibhav at vaibhav@example.com or connect on LinkedIn at linkedin.com/in/vaibhav.",
    resume: "Download Vaibhav's resume from the navigation bar or the Download Resume button in the hero section.",
  },
};
